### ISSUE TITLE
ubuntu 16.04 running issue

### ISSUE THREAD

**Issue by mlzboy** [SwyftG/Daily1024#2]
Traceback (most recent call last):
  File "./quick_start.py", line 14, in <module>
    main()
  File "./quick_start.py", line 10, in main
    spider.crawl_1024()
  File "/root/Daily1024/crawlspider/spider.py", line 34, in crawl_1024
    self.outputer.output_html()
  File "/root/Daily1024/crawlspider/html_outputer.py", line 53, in output_html
    result_root_file.write("<td><a href=\"%s\" target=\"_self\"> %s </a></td>" % (item_file_url,item_name))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-59: ordinal not in range(128)

**Comment by mlzboy** [comment]
due to my env is py2.7
